"""Unit tests for scripts/ada/cms-report-note.py — the session-side CMS
note writer (report-session-loop design §2c).

Covers the two contracts a card session relies on: the session-log
managed block is appended/created in the right place (before the
provenance footer), and the write merges old meta per the
writer_contract instead of bare-replacing it. Fully fake MDDB
transport — no network, no writes leave the test process.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
import urllib.error
import urllib.request
from pathlib import Path
from unittest import mock

REPO = Path(__file__).resolve().parents[2]
SCRIPT = REPO / "scripts/ada/cms-report-note.py"

NOW = 1791357331  # 2026-10-07


class Resp:
    def __init__(self, payload, status=200):
        self._b = json.dumps(payload).encode()
        self.status = status

    def read(self):
        return self._b

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False


class FakeMDDB:
    """In-process ada-cms-pages: /get /add /search — enough for
    cms-report-note + the reports-index regen it triggers."""

    def __init__(self):
        self.docs = {}   # (key, lang) -> doc
        self.adds = []   # add payloads, in order

    def seed(self, key, lang="en", md="# x", meta=None, added=NOW):
        self.docs[(key, lang)] = {
            "id": f"ada-cms-pages|{key}|{lang}", "key": key, "lang": lang,
            "contentMd": md, "meta": meta or {},
            "addedAt": added, "updatedAt": added}

    def handle(self, req, timeout=None):
        url = req.full_url if hasattr(req, "full_url") else req
        body = json.loads(req.data) if getattr(req, "data", None) else {}
        path = url.rsplit("/", 1)[-1]
        if path == "get":
            d = self.docs.get((body["key"], body["lang"]))
            if d is None:
                raise urllib.error.HTTPError(url, 400, "not found", {}, None)
            return Resp(d)
        if path == "search":
            all_docs = sorted(self.docs.values(),
                              key=lambda d: (d["key"], d["lang"]))
            off, lim = body.get("offset", 0), body.get("limit", 500)
            return Resp(all_docs[off:off + lim])
        if path == "add":
            self.adds.append(body)
            prev = self.docs.get((body["key"], body["lang"]))
            self.docs[(body["key"], body["lang"])] = {
                "id": f"ada-cms-pages|{body['key']}|{body['lang']}",
                "key": body["key"], "lang": body["lang"],
                "contentMd": body["contentMd"], "meta": body["meta"],
                "addedAt": (prev or {}).get("addedAt", NOW),
                "updatedAt": NOW}
            return Resp({"ok": True})
        raise AssertionError(f"unexpected url {url}")


PAGE_MD = (
    "# Dev Kanban\n\nLive board.\n\n"
    "| card | note |\n|---|---|\n| x | y |\n\n"
    "---\n*Generated by kanban-cms from docs/ssot/kanban/cards/*.yml.*\n")

BASE_META = {
    "bank": ["cms"], "scope": ["tony"], "kind": ["page"],
    "status": ["active"], "source": ["api"], "slug": ["dev-kanban"],
    "subject": ["dev-kanban"], "title": ["Dev Kanban"],
    "attribute": ["page"], "format": ["markdown"], "lang": ["en"],
    "valid_from": ["2026-10-05"], "last_verified": ["2026-10-06"],
    "written_by": ["kanban-cms"], "generated_by": ["kanban-cms"],
    "timeline": ["2026-10-06T10:00 seeded entry"],
    "updated": ["2026-10-07T04:30:22+00:00"],
}


class CmsReportNoteTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        spec = importlib.util.spec_from_file_location(
            "cms_report_note", SCRIPT)
        self.mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.mod)
        self.db = FakeMDDB()
        self._patch = mock.patch.object(
            urllib.request, "urlopen", side_effect=self.db.handle)
        self._patch.start()

    def tearDown(self):
        self._patch.stop()
        self.tmp.cleanup()

    def test_read_prints_title_meta_body(self):
        self.db.seed("dev-kanban", md=PAGE_MD, meta=dict(BASE_META))
        doc = self.mod.get_page("dev-kanban")
        self.assertEqual(doc["key"], "dev-kanban")

    def test_note_appends_into_existing_block(self):
        md = ("# X\n\n<!-- session-log:auto -->\n"
              "* 2026-10-07T10:00 — earlier note (session aaa)\n"
              "<!-- /session-log:auto -->\n\n"
              "---\n*Generated by x.*\n")
        self.db.seed("dev-kanban", md=md, meta=dict(BASE_META))
        self.mod.note("dev-kanban", "second note")
        out = self.db.docs[("dev-kanban", "en")]["contentMd"]
        block = self.mod.BLOCK_RE.search(out).group(0)
        self.assertIn("earlier note", block)
        self.assertIn("second note", block)
        self.assertLess(block.index("earlier note"),
                        block.index("second note"))
        # provenance footer survived, after the block
        self.assertIn("*Generated by x.*", out)
        self.assertLess(out.index("<!-- /session-log:auto -->"),
                        out.index("*Generated by x.*"))

    def test_note_creates_block_before_provenance_footer(self):
        self.db.seed("dev-kanban", md=PAGE_MD, meta=dict(BASE_META))
        self.mod.note("dev-kanban", "first note")
        out = self.db.docs[("dev-kanban", "en")]["contentMd"]
        self.assertIn("<!-- session-log:auto -->", out)
        self.assertIn("<!-- /session-log:auto -->", out)
        self.assertIn("first note", out)
        # block sits between the card table and the provenance footer
        self.assertLess(out.index("<!-- session-log:auto -->"),
                        out.index("*Generated by kanban-cms"))
        self.assertLess(out.index("| x | y |"),
                        out.index("<!-- session-log:auto -->"))

    def test_note_no_footer_appends_at_end(self):
        self.db.seed("dev-kanban", md="# X\n\nbody text\n",
                     meta=dict(BASE_META))
        self.mod.note("dev-kanban", "tail note")
        out = self.db.docs[("dev-kanban", "en")]["contentMd"]
        self.assertLess(out.index("body text"),
                        out.index("<!-- session-log:auto -->"))
        self.assertTrue(out.rstrip().endswith("<!-- /session-log:auto -->"))

    def test_meta_merge_preserves_schema_fields(self):
        self.db.seed("dev-kanban", md=PAGE_MD, meta=dict(BASE_META))
        self.mod.note("dev-kanban", "merge check")
        meta = self.db.docs[("dev-kanban", "en")]["meta"]
        # writer_contract: preserved or stamped, never bare-replaced
        for k, v in (("bank", "cms"), ("scope", "tony"),
                     ("status", "active"), ("source", "api"),
                     ("subject", "dev-kanban"), ("attribute", "page"),
                     ("valid_from", "2026-10-05"),
                     ("generated_by", "kanban-cms")):
            self.assertEqual(meta.get(k), [v], k)
        self.assertEqual(meta["written_by"], ["cms-report-note.py"])
        self.assertNotEqual(meta["updated"], BASE_META["updated"])
        self.assertEqual(meta["last_verified"][0][:10],
                         meta["updated"][0][:10])
        # timeline: appended, capped at 40
        tl = meta["timeline"]
        self.assertEqual(len(tl), 2)
        self.assertEqual(tl[0], "2026-10-06T10:00 seeded entry")

    def test_timeline_capped_at_40(self):
        meta = dict(BASE_META)
        meta["timeline"] = [f"e{i:02d}" for i in range(40)]
        self.db.seed("dev-kanban", md=PAGE_MD, meta=meta)
        self.mod.note("dev-kanban", "cap check")
        tl = self.db.docs[("dev-kanban", "en")]["meta"]["timeline"]
        self.assertEqual(len(tl), 40)
        self.assertNotIn("e00", tl)

    def test_session_tag_from_task_id_env(self):
        self.db.seed("dev-kanban", md=PAGE_MD, meta=dict(BASE_META))
        with mock.patch.dict("os.environ",
                             {"TASK_ID": "20990101-000000-x"}, clear=False):
            self.mod.note("dev-kanban", "tagged")
        out = self.db.docs[("dev-kanban", "en")]["contentMd"]
        self.assertIn("(session 20990101-000000-x)", out)

    def test_regen_reports_index_called(self):
        self.db.seed("dev-kanban", md=PAGE_MD, meta=dict(BASE_META))
        self.mod.note("dev-kanban", "index check")
        keys = [a["key"] for a in self.db.adds]
        self.assertEqual(keys[0], "dev-kanban")
        self.assertIn("reports-index", keys)

    def test_missing_page_raises(self):
        with self.assertRaises(SystemExit):
            self.mod.note("no-such-page", "x")


if __name__ == "__main__":
    unittest.main()
