#!/usr/bin/env python3
"""CMS page audit — mechanical quality gate for ada-cms-pages.

Rules (docs-as-code adapted):
  A1 non-empty body (>200c)
  A2 meta complete: slug,title,format,updated,kind=page
  A3 H1 present and matches title-ish
  A4 markdown structure: at least one heading or list
  A5 no placeholder markers (TODO/TBD/lorem/placeholder/draft)
  A6 no secrets (token/password/key= patterns)
  N* news-* pages: TL;DR line, <=6 items, source links, "why it matters"
  R* generated-report standard (docs/ssot/apps/ssot.apps.cms-reports.yml)
    — applies only to docs whose meta carries generated_by:
    R1 generated_by set but sources empty
    R2 no provenance footer (Generated by|รวบรวมอัตโนมัติ|สร้างโดย)
    R3 meta.parent/children slug not found in the collection
    R4 unbalanced <!-- X:auto --> managed-block markers
    R5 warn: no registry doc in ada-cms-automation (live mode only)
    R6 warn: report_role vs children inference disagree
  C* consolidation/obsolete (warnings, not failures):
    C1 near-duplicate slug pairs (>=70% token overlap) — merge candidates
    C2 stale living page: `updated` older than STALE_DAYS
  S* memory-schema conformance (warnings, not failures):
    S1 doc missing schema fields — run scripts/ada/cms-normalize-meta.py
       (fields: bank, scope, status, source, written_by, subject,
        attribute, valid_from, last_verified)

CI mode: --file <backup dump> audits a repo snapshot instead of live MDDB
(backups/ada-memory/ada-cms-pages.json written by backup-mddb-banks.py).
--baseline <json> maps {slug: [rules]} of known failures — exits nonzero
on NEW failures AND on stale baseline entries (a fixed page must drop
from the baseline — the ratchet only moves toward zero).
"""
import datetime, json, os, re, sys, urllib.request

MDDB = os.environ.get("MDDB_BASE_URL", "http://100.74.146.0:11023/v1")
STALE_DAYS = int(os.environ.get("CMS_AUDIT_STALE_DAYS", "14"))
# Living pages exempt from C2 staleness — point-in-time reports are
# SUPPOSED to be dated. Opt out by keeping a -report/-assessment/-proposal
# suffix, or add the slug here.
REPORT_SLUG_RE = re.compile(r"(report|assessment|proposal|analysis|review|incident|demo)$")
# Memory-schema fields every page should carry after cms-normalize-meta.py.
SCHEMA_FIELDS = ("bank", "scope", "status", "source", "written_by",
                 "subject", "attribute", "valid_from", "last_verified")

def get_pages():
    req = urllib.request.Request(f"{MDDB}/search",
        data=json.dumps({"collection": "ada-cms-pages", "filter_meta": {"kind": ["page"]}, "limit": 200}).encode(),
        headers={"Content-Type": "application/json"})
    return json.load(urllib.request.urlopen(req, timeout=60))


def load_snapshot(path):
    """backup-mddb-banks.py dump: {collection, exported_at, docs:[...]}"""
    data = json.load(open(path))
    docs = data.get("docs") if isinstance(data, dict) else data
    if not isinstance(docs, list):
        raise SystemExit(f"error: {path} has no docs list")
    return [d for d in docs
            if (d.get("meta") or {}).get("kind", ["page"])[0] == "page"
            or (d.get("meta") or {}).get("kind") is None]


PROVENANCE_RE = re.compile(r"generated by|รวบรวมอัตโนมัติ|สร้างโดย", re.I)
AUTO_OPEN_RE = re.compile(r"<!--\s*([\w-]+):auto\s*-->")
AUTO_CLOSE_RE = re.compile(r"<!--\s*/([\w-]+):auto\s*-->")


def report_rules(doc, slugs):
    """R-rules — generated-report standard. Caller must gate on
    meta.generated_by (hand-maintained pages are exempt).
    Returns (fails, warns)."""
    meta = doc.get("meta") or {}
    fails, warns = [], []
    first = lambda f: (meta.get(f) or [""])[0]
    if not meta.get("sources"):
        fails.append("R1:no-sources")
    if not PROVENANCE_RE.search(doc.get("contentMd") or ""):
        fails.append("R2:no-provenance-footer")
    for f in ("parent",):
        if meta.get(f) and first(f) not in slugs:
            fails.append(f"R3:dangling-{f}({first(f)})")
    for c in meta.get("children") or []:
        if c not in slugs:
            fails.append(f"R3:dangling-children({c})")
    opens = AUTO_OPEN_RE.findall(doc.get("contentMd") or "")
    closes = AUTO_CLOSE_RE.findall(doc.get("contentMd") or "")
    if sorted(opens) != sorted(closes):
        fails.append("R4:unbalanced-auto-block")
    role = first("report_role")
    if role and ((role == "rollup") != bool(meta.get("children"))):
        warns.append(f"R6:role-mismatch({role})")
    return fails, warns

def audit(doc, slugs=()):
    key = doc["key"]; body = doc.get("contentMd") or ""
    meta = doc.get("meta") or {}
    fails = []
    if len(body.strip()) < 200: fails.append("A1:empty-or-thin")
    for f in ("slug", "title", "format", "updated"):
        if not meta.get(f): fails.append(f"A2:missing-{f}")
    if (meta.get("kind") or [""])[0] != "page": fails.append("A2:kind!=page")
    h1 = re.search(r"^#\s+(.+)$", body, re.M)
    if not h1: fails.append("A3:no-h1")
    else:
        title = (meta.get("title") or [""])[0].lower()
        words = [w for w in re.findall(r"[a-z]+", title) if len(w) > 3]
        if words and not any(w in h1.group(1).lower() for w in words): fails.append("A3:h1-title-mismatch")
    if not re.search(r"^(#{1,3}\s|[-*]\s)", body, re.M): fails.append("A4:no-structure")
    # A5 is skipped on the audit's own report — its body lists rule names
    # like "A5:placeholder" verbatim and would fail itself every run.
    # TODO/TBD stay case-sensitive (uppercase marker convention) so a page
    # titled "Todo List" doesn't flag itself; lorem/placeholder insensitive.
    if key != "cms-audit-report" and re.search(
            r"\b(?:TODO|TBD)\b|(?i:lorem ipsum|placeholder)", body): fails.append("A5:placeholder")
    # A6: flag only values that look like real secrets — 16+ mixed-case
    # chars or digits — so identifier names like Secret=cf_tunnel_token or
    # prose ("copy the token") don't trip it.
    if re.search(r"(api[_-]?key|password|secret|token)\s*[:=]\s*[\"']?"
                 r"(?=[A-Za-z0-9_\-]{16,})(?=[A-Za-z0-9_\-]*[0-9A-Z])",
                 body, re.I):
        v = re.search(r"(?:api[_-]?key|password|secret|token)\s*[:=]\s*[\"']?"
                      r"([A-Za-z0-9_\-]+)", body, re.I)
        if v and not re.fullmatch(r"[a-z_]+", v.group(1)):
            fails.append("A6:secret-ish")
    # N-rules apply to news-* digests only. Pages normalized by
    # cms-normalize-meta.py carry attribute — a news-* slug classed as
    # e.g. attribute=assessment (news-source-assessment) is exempt.
    attr = (meta.get("attribute") or [""])[0]
    if key.startswith("news-") and attr in ("", "news"):
        if "TL;DR" not in body: fails.append("N1:no-tldr")
        items = len(re.findall(r"^[-*]\s", body, re.M))
        if key != "news-system" and items > 6: fails.append(f"N2:too-many-items({items})")
        if key not in ("news-system",) and not re.search(r"\[source|\(http", body, re.I):
            fails.append("N3:no-source-links")
        if key not in ("news-system", "news-headline") and not re.search(r"why it matters|why:|impact", body, re.I):
            fails.append("N4:no-why-it-matters")
    if meta.get("generated_by"):
        rf, _ = report_rules(doc, slugs)
        fails += rf
    return fails


def slug_tokens(slug: str) -> set[str]:
    return {t for t in re.split(r"[-_]+", slug.lower()) if len(t) > 2}


def body_tokens(body: str) -> set[str]:
    """Content words for C1 body-similarity — strips markdown syntax and
    very common glue words so prose overlap reflects real duplication."""
    words = re.findall(r"[A-Za-zก-๙]{4,}", body.lower())
    stop = {"with", "that", "this", "from", "have", "been", "they", "their",
            "will", "would", "could", "should", "http", "https", "com"}
    return {w for w in words if w not in stop}


def consolidation_warnings(docs: list[dict]) -> list[str]:
    """C-rules — warnings, never failures.

    C1: near-duplicate slug pairs — >=70% token overlap suggests two
        pages covering the same subject (merge or supersede one).
    C2: living page whose `updated` is older than STALE_DAYS and is not
        a point-in-time report slug — obsolete content likely.
    """
    warns: list[str] = []
    today = datetime.date.today()
    docs_by_key = {d["key"]: d for d in docs}
    toks = {d["key"]: slug_tokens(d["key"]) for d in docs}
    keys = sorted(toks)
    for i, key in enumerate(keys):
        for other in keys[i + 1:]:
            a, b = toks[key], toks[other]
            if not a or not b:
                continue
            overlap = len(a & b) / len(a | b)
            if overlap >= 0.7:
                # Slug similarity alone false-positives on dated series
                # (transcript-audit-09-28/09-29), per-owner twins
                # (my-words / my-words-kk) and auto-generated siblings
                # (vms-noble-club / wall-vms-noble-club). Only flag when
                # the bodies substantially overlap too.
                ba = body_tokens(docs_by_key[key].get("contentMd") or "")
                bb = body_tokens(docs_by_key[other].get("contentMd") or "")
                if not ba or not bb:
                    continue
                sim = len(ba & bb) / len(ba | bb)
                if sim >= 0.6:
                    warns.append(
                        f"C1 duplicate-ish: {key} ~ {other} "
                        f"({overlap:.0%} slug, {sim:.0%} body overlap)")
        meta = docs_by_key[key].get("meta") or {}
        upd = (meta.get("updated") or [""])[0][:10]
        if upd and not REPORT_SLUG_RE.search(key):
            try:
                age = (today - datetime.date.fromisoformat(upd)).days
                if age > STALE_DAYS:
                    warns.append(f"C2 stale {key}: last updated {upd} ({age}d ago)")
            except ValueError:
                pass
    return warns


def schema_warnings(docs: list[dict]) -> list[str]:
    """S-rules — memory-schema conformance, warnings only."""
    warns: list[str] = []
    for d in sorted(docs, key=lambda x: x["id"]):
        meta = d.get("meta") or {}
        missing = [f for f in SCHEMA_FIELDS if not meta.get(f)]
        if missing:
            warns.append(f"S1 {d['id']}: missing schema meta {', '.join(missing)}")
    return warns


def report_warnings(docs: list[dict], live: bool) -> list[str]:
    """R5/R6 — generated-report warnings. R5 needs the live registry
    collection, so it's skipped in --file mode."""
    warns: list[str] = []
    slugs = {d["key"] for d in docs}
    registry_keys = set()
    if live:
        try:
            req = urllib.request.Request(
                f"{MDDB}/search",
                data=json.dumps({"collection": "ada-cms-automation",
                                 "limit": 500}).encode(),
                headers={"Content-Type": "application/json"})
            registry_keys = {d["key"] for d in
                             json.load(urllib.request.urlopen(req, timeout=60))}
        except Exception as e:
            print(f"warn: registry check skipped ({e})", file=sys.stderr)
    for d in docs:
        meta = d.get("meta") or {}
        if not meta.get("generated_by"):
            continue
        _, rw = report_rules(d, slugs)
        warns += [f"{d['id']}: {w}" for w in rw]
        # report-distill digests refresh via the report-distill.service
        # systemd timer (bulk job) — they have no per-page registry config,
        # so requiring an ada-cms-automation doc is a false positive.
        gen = (meta.get("generated_by") or [""])[0]
        if live and gen != "report-distill" and d["key"] not in registry_keys:
            warns.append(f"{d['id']}: R5:no-registry-doc")
    return warns

def publish(lines: list[str], passed: int, failed: int) -> None:
    """Upsert results to ada-cms-pages/cms-audit-report — preserving
    existing meta (normalized schema fields, provenance)."""
    import datetime
    body = ("# CMS audit\n\nRun " +
            datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds") +
            f" — {passed} pass, {failed} fail\n\n```\n" + "\n".join(lines) + "\n```\n")
    now = datetime.datetime.now(datetime.timezone.utc)
    meta = {"kind": ["page"], "slug": ["cms-audit-report"],
            "title": ["CMS Audit Report"], "format": ["markdown"],
            "instance": ["cms-audit"],
            "generated_by": ["cms-audit.py --publish"],
            "sources": ["ada-cms-pages"],
            "report_role": ["leaf"]}
    try:  # merge existing doc meta so schema fields survive the rewrite
        req = urllib.request.Request(
            f"{MDDB}/get",
            data=json.dumps({"collection": "ada-cms-pages",
                             "key": "cms-audit-report", "lang": "en"}).encode(),
            headers={"Content-Type": "application/json"})
        old = json.load(urllib.request.urlopen(req, timeout=30))
        old_meta = {k: (v if isinstance(v, list) else [str(v)])
                    for k, v in (old.get("meta") or {}).items()}
        old_meta.update(meta)  # tool-owned fields win; schema fields survive
        meta = old_meta
    except Exception:
        pass
    meta["updated"] = [now.isoformat(timespec="seconds")]
    meta["last_verified"] = [now.date().isoformat()]
    payload = {"collection": "ada-cms-pages", "key": "cms-audit-report",
               "lang": "en", "contentMd": body, "meta": meta}
    req = urllib.request.Request(f"{MDDB}/add",
        data=json.dumps(payload).encode(), headers={"Content-Type": "application/json"})
    urllib.request.urlopen(req, timeout=30)


def main():
    import argparse
    ap = argparse.ArgumentParser(description="Audit ada-cms-pages quality + standards")
    ap.add_argument("--file", help="audit a backup dump instead of live MDDB (CI mode)")
    ap.add_argument("--baseline",
                    help="JSON {slug: [rules]} of known failures — ratchet: exit 1 "
                         "on new fails or stale baseline entries")
    ap.add_argument("--publish", action="store_true")
    ap.add_argument("--match", help="only audit slugs with this prefix")
    args = ap.parse_args()

    live = not args.file
    pages = load_snapshot(args.file) if args.file else get_pages()
    slugs = {d["key"] for d in pages}
    results = {}  # slug -> [fails]
    lines, passed = [], 0
    for d in sorted(pages, key=lambda x: (x["key"], x.get("lang") or "")):
        if args.match and not d["key"].startswith(args.match):
            continue
        fails = audit(d, slugs)
        results.setdefault(d["key"], [])
        results[d["key"]] = sorted(set(results[d["key"]] + fails))
        if fails:
            lines.append(f"FAIL {d.get('id') or d['key']:42} {', '.join(fails)}")
        else:
            passed += 1
            lines.append(f"pass {d.get('id') or d['key']:42} {len(d.get('contentMd') or '')}c")
    failed = sum(1 for v in results.values() if v)
    warns = [] if args.match else (
        consolidation_warnings(pages) + schema_warnings(pages)
        + report_warnings(pages, live))
    lines.append(f"\n{passed} pass · {failed} fail · {len(warns)} warnings")
    if warns:
        lines.append("\n## Warnings")
        lines.extend(warns)
    print("\n".join(lines))
    if args.publish:
        publish(lines, passed, failed)
        print("published -> ada-cms-pages/cms-audit-report")

    if args.baseline:
        base = {k: v for k, v in json.load(open(args.baseline)).items()
                if not k.startswith("_")}
        new_fails = {k: v for k, v in results.items()
                     if sorted(v) != sorted(base.get(k, [])) and v}
        stale = [k for k, v in base.items()
                 if not v or sorted(results.get(k, [])) != sorted(v)]
        rc = 0
        if new_fails:
            print("\nNEW failures not in baseline:")
            for k, v in new_fails.items():
                print(f"  {k}: {', '.join(v)}")
            rc = 1
        if stale:
            print("\nStale baseline entries (page changed — update the baseline):")
            for k in stale:
                print(f"  {k}: was {base[k]}, now {results.get(k, [])}")
            rc = 1
        if not rc:
            print("\nbaseline ratchet OK — no new failures")
        sys.exit(rc)
    sys.exit(0 if failed == 0 else 1)


main()
