#!/usr/bin/env python3
"""cms-report-note.py — session-side note writer for ada-cms-pages.

The chaba-repo twin of Ada's cms_note_update tool: a dispatch session whose
card carries `report: <slug>` (REPORT_RAILS in kanban-dispatch.py) reads the
report first, then appends progress lines here instead of hand-rolling MDDB
writes. Report↔card sync is by convention — this script keeps the write
honest: managed session-log block, meta.timeline append (cap 40), full
writer_contract meta merge (never bare-replace), reports-index regen.

Usage:
  cms-report-note.py <slug> --read            # title + key meta + body
  cms-report-note.py <slug> --note "<text>"   # append a session-log line
  cms-report-note.py <slug> --note "…" --lang th

Env:
  MDDB_BASE_URL   default http://100.102.134.91:11023/v1
  TASK_ID         stamped on the note line; falls back to basename(TASK_DIR)
"""
from __future__ import annotations

import argparse
import datetime
import importlib.util
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))

MDDB = os.environ.get("MDDB_BASE_URL",
                      "http://100.102.134.91:11023/v1").rstrip("/")
COLLECTION = "ada-cms-pages"
WRITTEN_BY = "cms-report-note.py"
BLOCK_BEGIN = "<!-- session-log:auto -->"
BLOCK_END = "<!-- /session-log:auto -->"
BLOCK_RE = re.compile(re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END),
                      re.S)
# Same phrases cms-audit.py's R2 provenance rule accepts.
PROVENANCE_RE = re.compile(r"generated by|รวบรวมอัตโนมัติ|สร้างโดย", re.I)
SOURCE_ENUM = {"voice", "manual", "import", "extract", "api"}
TIMELINE_CAP = 40  # ssot.apps.ada-cms-reports.yml meta_contract.timeline


def _post(path: str, payload: dict, timeout: int = 30):
    req = urllib.request.Request(
        f"{MDDB}/{path}", data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"})
    return json.load(urllib.request.urlopen(req, timeout=timeout))


def get_page(slug: str, lang: str = "en") -> dict | None:
    try:
        return _post("get", {"collection": COLLECTION, "key": slug,
                             "lang": lang})
    except urllib.error.HTTPError as e:
        if e.code in (400, 404):
            return None
        raise


def _first(meta: dict, name: str) -> str:
    v = (meta or {}).get(name)
    if isinstance(v, list):
        return str(v[0]) if v else ""
    return str(v) if v else ""


def page_type(slug: str) -> str:
    """attribute value the writer_contract requires — the same answer
    cms-normalize-meta.py computes so the next normalize pass is a no-op."""
    try:
        spec = importlib.util.spec_from_file_location(
            "cms_normalize_meta", REPO / "scripts/ada/cms-normalize-meta.py")
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod.page_type(slug)
    except Exception:
        return "page"


def session_tag() -> str:
    """' (session <task-id>)' suffix when running inside devin-dispatch."""
    tid = os.environ.get("TASK_ID") or os.path.basename(
        os.environ.get("TASK_DIR", "").rstrip("/"))
    return f" (session {tid})" if tid else ""


def note_line(text: str, now: datetime.datetime) -> str:
    ts = now.strftime("%Y-%m-%dT%H:%M")  # same minute-precision ISO as
    # cms_note_update's meta.timeline entries
    body = " ".join(text.split())  # one bullet per call — keep lines atomic
    return f"* {ts} — {body}{session_tag()}"


def apply_session_log(body: str, line: str) -> str:
    """Append `line` inside the managed block; create the block just before
    the provenance footer (or at EOF) when absent. Append-only — callers
    wanting dedup should diff the doc first."""
    if BLOCK_RE.search(body):
        def repl(m: re.Match) -> str:
            inner = m.group(0)
            head = inner[: inner.rfind(BLOCK_END)].rstrip()
            return f"{head}\n{line}\n{BLOCK_END}"
        return BLOCK_RE.sub(repl, body, count=1)
    block = f"{BLOCK_BEGIN}\n{line}\n{BLOCK_END}"
    lines = body.rstrip("\n").splitlines()
    prov = None
    for i, l in enumerate(lines):
        if PROVENANCE_RE.search(l):
            prov = i
    if prov is not None:
        start = prov
        if start > 0 and lines[start - 1].strip() == "---":
            start -= 1
        ins = ([""] if start > 0 and lines[start - 1].strip() else [])
        ins += [block, ""]
        lines[start:start] = ins
    else:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append(block)
    return "\n".join(lines) + "\n"


def merged_meta(doc: dict, slug: str, now: datetime.datetime,
                today: str) -> dict:
    """writer_contract (ssot.apps.cms-reports.yml): merge — never bare-
    replace; bank/scope/status/source/written_by/subject/attribute/
    valid_from/last_verified preserved or stamped, updated stamped."""
    meta = {k: (v if isinstance(v, list) else [str(v)])
            for k, v in (doc.get("meta") or {}).items()}
    added = ""
    if doc.get("addedAt"):
        added = datetime.datetime.fromtimestamp(
            doc["addedAt"], datetime.timezone.utc).date().isoformat()
    meta.update({
        "bank": ["cms"], "scope": ["tony"],
        "status": meta.get("status") or ["active"],
        "source": (meta["source"] if _first(meta, "source") in SOURCE_ENUM
                   else ["api"]),
        "written_by": [WRITTEN_BY],
        "subject": [slug], "attribute": [page_type(slug)],
        "valid_from": meta.get("valid_from") or [added or today],
        "last_verified": [today],
        "updated": [now.isoformat(timespec="seconds")],
        "lang": meta.get("lang") or [doc.get("lang") or "en"],
        "format": meta.get("format") or ["markdown"],
        "kind": meta.get("kind") or ["page"],
    })
    tl = [x for x in meta.get("timeline", []) if isinstance(x, str)]
    tl.append(f"{now.isoformat(timespec='seconds')[:16]} session note")
    meta["timeline"] = tl[-TIMELINE_CAP:]
    return meta


def note(slug: str, text: str, lang: str = "en",
         regen: bool = True) -> dict:
    doc = get_page(slug, lang)
    if not isinstance(doc, dict):
        raise SystemExit(
            f"cms-report-note: no such page ada-cms-pages/{slug} ({lang}) "
            "— create it via cms_publish_page")
    now = datetime.datetime.now(datetime.timezone.utc)
    today = now.date().isoformat()
    line = note_line(text, now)
    body = apply_session_log(doc.get("contentMd") or "", line)
    meta = merged_meta(doc, slug, now, today)
    _post("add", {"collection": COLLECTION, "key": slug,
                  "lang": doc.get("lang") or lang,
                  "contentMd": body, "meta": meta}, timeout=60)
    if regen:
        # raw /v1/add never triggers ada-pi's _cms_reports_index — regen
        # here like report-daily-brief.py/cam-wall-cms.py do.
        from lib.cms_index import regen_reports_index
        regen_reports_index(MDDB, written_by=WRITTEN_BY)
    return {"slug": slug, "line": line,
            "timeline_entries": len(meta["timeline"]),
            "updated": _first(meta, "updated")}


def print_page(doc: dict) -> None:
    meta = doc.get("meta") or {}
    keys = ("title", "kind", "status", "domain", "updated", "fresh_for",
            "confidence", "summary", "written_by")
    for k in keys:
        v = _first(meta, k)
        if v:
            print(f"{k}: {v}")
    tl = meta.get("timeline")
    if tl:
        print(f"timeline: {len(tl)} entr{'y' if len(tl) == 1 else 'ies'}")
    print("---")
    print(doc.get("contentMd") or "")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("slug", help="ada-cms-pages key, e.g. dev-kanban")
    p.add_argument("--lang", default="en")
    p.add_argument("--read", action="store_true",
                   help="print title, key meta fields and the page body")
    p.add_argument("--note", metavar="TEXT",
                   help="append a session-log line + meta.timeline entry")
    args = p.parse_args()

    if args.read:
        doc = get_page(args.slug, args.lang)
        if not isinstance(doc, dict):
            print(f"no such page: ada-cms-pages/{args.slug} ({args.lang})",
                  file=sys.stderr)
            return 1
        print_page(doc)
        return 0
    if args.note is not None:
        r = note(args.slug, args.note, args.lang)
        print(f"noted {r['slug']}: {r['line']}")
        print(f"timeline={r['timeline_entries']} updated={r['updated']}")
        return 0
    p.error("one of --read / --note is required")


if __name__ == "__main__":
    sys.exit(main())
