#!/usr/bin/env python3
"""Export Ada voice transcripts from a runtime host for offline review.

Ada (ada-pi >= transcript persistence) archives raw voice-session
transcripts to ADA_TRANSCRIPT_DIR (default ~/.local/share/ada/transcripts)
on the host running ada-ha-*.service. This script pulls them to a local
review directory so a Devin session can audit conversation quality —
missed recalls, wrong tool choices, missed action items, prompt gaps.

Privacy: transcripts can contain private details and credential-shaped
text. The output directory is intentionally outside the repo and must
never be committed. Keep it that way.

Usage:
  export-transcripts.py                    # pull from mn01 (default host)
  export-transcripts.py --host idc01
  export-transcripts.py --since 2026-09-20 --limit 20
  export-transcripts.py --local /path/to/transcripts   # no ssh, copy local
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

REMOTE_DIR = "~/.local/share/ada/transcripts"
DEFAULT_OUT = Path.home() / ".local/share/ada-review/transcripts"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--host", default="mn01",
                    help="ada runtime host to pull from (mn01|idc01|tony-dell)")
    ap.add_argument("--local", type=Path, default=None,
                    help="read transcripts from a local dir instead of ssh")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--remote-dir", default=REMOTE_DIR)
    ap.add_argument("--since", default=None,
                    help="only transcripts dated >= YYYY-MM-DD (filename prefix)")
    ap.add_argument("--limit", type=int, default=50,
                    help="max most-recent transcripts to copy")
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    if args.local is not None:
        src = args.local.expanduser()
        files = sorted(p for p in src.glob("*.md") if p.is_file())
    else:
        # List remote transcript files, newest first.
        try:
            out = subprocess.run(
                ["ssh", args.host,
                 f"ls -1 {args.remote_dir}/*.md 2>/dev/null | sort -r"],
                capture_output=True, text=True, timeout=30, check=True,
            )
        except subprocess.CalledProcessError as exc:
            print(f"ssh listing failed on {args.host}: {exc.stderr.strip()}",
                  file=sys.stderr)
            return 1
        files = [Path(line.strip()) for line in out.stdout.splitlines()
                 if line.strip()]

    if args.since:
        files = [p for p in files if p.name >= args.since]
    files = files[: args.limit]
    if not files:
        print("no transcripts found")
        return 0

    copied = []
    if args.local is not None:
        for p in files:
            dst = args.out / p.name
            if not dst.exists() or dst.stat().st_size != p.stat().st_size:
                shutil.copy2(p, dst)
            copied.append(dst.name)
    else:
        # Filenames are generated by Ada (date + sanitized session id), so
        # plain per-file scp is safe and lossless.
        for p in files:
            r = subprocess.run(
                ["scp", "-q", f"{args.host}:{args.remote_dir}/{p.name}",
                 str(args.out / p.name)],
                timeout=60,
            )
            if r.returncode == 0:
                copied.append(p.name)

    manifest = args.out / "MANIFEST.txt"
    with manifest.open("w") as fh:
        fh.write(f"host={args.host} local={args.local or '-'} "
                 f"pulled={len(copied)}\n")
        for name in copied:
            fh.write(f"{name}\n")
    print(f"copied {len(copied)} transcript(s) -> {args.out}")
    print(f"manifest: {manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
