#!/usr/bin/env python3
"""report-distill.py — nightly L1 bank -> L2 CMS report promotion.

Deterministic per-domain rollup (no LLM in v1). For each domain found in
ada-cms-pages:

  1. Members — docs with meta.domain=<domain> and kind report|page,
     status active only (superseded/archived/retracted drop out).
  2. Bank deltas — docs added/updated in the domain's source collections
     since the last run (registry last_run, else the page's own
     meta.updated, else 24h ago). Private/person-scoped banks report
     counts only — never keys/titles/bodies — per the privacy rule in
     ssot.apps.ada-cms-reports.yml.
  3. Refresh ada-cms-pages/<domain>-digest as kind:report carrying the
     full meta_contract (summary, domain, fresh_for, confidence,
     timeline, links, supersedes, updated) plus the memory-schema and
     provenance fields the writer contract requires.
  4. Supersede chain — when the previous digest's meta.updated is from
     an earlier date, its content is first archived to
     <domain>-digest-YYYY-MM-DD (status: superseded, superseded_by:
     <domain>-digest) and the fresh page's supersedes points at it.
     Archives older than KEEP_DAYS flip to status: archived so indexes
     and domain scans stay clean.
  5. Registry — ada-cms-automation/<domain>-digest carries the knobs
     (enabled, interval_min, run_now) and gets last_* write-back, so
     cms-auto-health.py turns a stale/erroring distill into a kanban
     card. Missing docs are seeded with defaults.
  6. reports-index is regenerated once after all domains publish — raw
     /v1/add never triggers ada-pi's own index refresh.

v1: `health` is the template domain — its digest adds a "bank deltas"
section covering every ada-ha-bank-* collection (enumerated from
ssot.apps.ada-memory-banks.yml) plus ops events and scenario reports.
Other domains get the same page shape minus the delta section until a
DOMAINS entry opts them in.

Usage:
  report-distill.py                  # every domain found in ada-cms-pages
  report-distill.py --domain health  # one domain (repeatable)
  report-distill.py --register       # seed missing registry docs, no run
  report-distill.py --dry-run        # render, no writes
  report-distill.py --force          # ignore interval_min/run_now gating

Env:
  MDDB_BASE_URL   default http://100.102.134.91:11023/v1
  CHABA_REPO      repo root holding docs/ssot (default: ../.. of script)
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

MDDB = os.environ.get(
    "MDDB_BASE_URL", "http://100.102.134.91:11023/v1").rstrip("/")
COLLECTION = "ada-cms-pages"
REGISTRY = "ada-cms-automation"
REPO = Path(os.environ.get(
    "CHABA_REPO", str(Path(__file__).resolve().parents[2])))
BANKS_SSOT = REPO / "docs" / "ssot" / "apps" / "ssot.apps.ada-memory-banks.yml"

# Pages that must never appear as digest members.
SKIP_KEYS = {"reports-index", "domains-overview"}
DEAD_STATUS = {"superseded", "archived", "retracted", "expired"}
# Collections whose contents are person-scoped or transcript-bearing —
# delta rows show counts only, never keys/titles.
PRIVATE_COLL_RX = re.compile(r"personal|devin|recall-summary|note-")
MAX_MEMBERS = 30      # rendered rows per domain digest
MAX_LINKS = 20        # meta.links cap
MAX_DELTAS = 10       # rendered rows per source collection
KEEP_DAYS = 14        # dated archives older than this flip to archived
DEFAULT_INTERVAL_MIN = 24 * 60
TIMELINE_CAP = 40

# Per-domain config — v1 template is `health`: the digest doubles as the
# memory-layer pulse, so its delta sources are every bank plus the two
# operational collections. Later domains opt in with their own entry.
DOMAINS = {
    "health": {
        "title": "Health",
        "fresh_for": "1d",
        "banks": True,  # enumerate ada-ha-bank-* from the SSOT registry
        "collections": ["ada-ha-ops-events", "ada-ha-scenario-reports"],
    },
}
DEFAULT_CFG = {"fresh_for": "1d", "banks": False, "collections": []}

_ARCHIVE_KEY_RX = re.compile(r"^(.*)-digest-(\d{4}-\d{2}-\d{2})$")
_COLL_KEY_RX = re.compile(r"^\s*mddb_collection:\s*(\S+)", re.M)
_VOLATILE_RX = re.compile(
    r"^(# .*— \d{4}-\d{2}-\d{2} \d{2}:\d{2}Z|\*\*Updated:\*\*.*"
    r"|\*Generated by report-distill.*)$", re.M)


def _post(path: str, payload: dict, timeout: int = 60):
    req = urllib.request.Request(
        f"{MDDB}/{path}", data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def _search_all(collection: str, page_size: int = 500) -> list[dict]:
    docs, offset = [], 0
    while True:
        page = _post("search", {"collection": collection, "query": "",
                                "limit": page_size, "offset": offset})
        if isinstance(page, dict):
            page = page.get("documents") or page.get("docs") or []
        docs += page
        if len(page) < page_size:
            return docs
        offset += page_size


def _meta(doc: dict, name: str) -> str:
    v = (doc.get("meta") or {}).get(name)
    if isinstance(v, list):
        return str(v[0]) if v else ""
    return str(v) if isinstance(v, (str, int, float)) else ""


def _meta_list(doc: dict, name: str) -> list[str]:
    v = (doc.get("meta") or {}).get(name)
    if isinstance(v, list):
        return [str(x) for x in v]
    return [v] if isinstance(v, str) and v else []


def fresh_for_seconds(hint: str) -> int | None:
    """'30m'/'1h'/'6h'/'1d'/'7d' -> seconds (report_meta.py parity)."""
    m = re.match(r"^(\d+(?:\.\d+)?)([mhd])$", (hint or "").strip().lower())
    if not m:
        return None
    return int(float(m.group(1)) * {"m": 60, "h": 3600, "d": 86400}[m.group(2)])


def is_stale(doc: dict, now: datetime) -> bool:
    ttl = fresh_for_seconds(_meta(doc, "fresh_for"))
    if ttl is None:
        return False
    try:
        up = datetime.fromisoformat(_meta(doc, "updated").replace("Z", "+00:00"))
        return (now - up).total_seconds() > ttl
    except (ValueError, TypeError):
        return False


def _epoch(doc: dict) -> float:
    """Doc freshness epoch — updatedAt else addedAt else 0."""
    for f in ("updatedAt", "addedAt"):
        v = doc.get(f)
        if isinstance(v, (int, float)):
            return float(v)
        if isinstance(v, str):
            try:
                return datetime.fromisoformat(
                    v.replace("Z", "+00:00")).timestamp()
            except ValueError:
                continue
    return 0.0


def _parse_ts(raw) -> float | None:
    """Registry last_run can be epoch or ISO (cms-auto-health parity)."""
    if isinstance(raw, (int, float)):
        return float(raw)
    if not raw:
        return None
    try:
        dt = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return None
    return dt.timestamp() if dt.tzinfo else time.mktime(dt.timetuple())


# ------------------------------------------------------------- registry

def list_registry() -> tuple[dict, bool]:
    """ada-cms-automation docs keyed by slug. MDDB down -> ({}, False)."""
    try:
        docs = _search_all(REGISTRY)
    except Exception as e:
        print(f"warn: automation registry unreachable ({e})",
              file=sys.stderr)
        return {}, False
    out = {}
    for d in docs:
        try:
            out[d["key"]] = json.loads(d.get("contentMd") or "{}")
        except (KeyError, json.JSONDecodeError) as e:
            print(f"warn: bad registry doc {d.get('id')}: {e}",
                  file=sys.stderr)
    return out, True


def save_registry_doc(page: str, cfg: dict) -> None:
    body = json.dumps(cfg, ensure_ascii=False, indent=2)
    now = datetime.now(timezone.utc)
    meta = {"kind": ["automation-config"], "bank": ["cms"], "scope": ["tony"],
            "status": ["active"], "source": ["api"],
            "written_by": ["report-distill.py"], "subject": [page],
            "attribute": ["automation"], "slug": [page],
            "title": [f"CMS automation: {page}"], "format": ["json"],
            "lang": ["en"], "updated": [now.isoformat(timespec="seconds")],
            "last_verified": [now.date().isoformat()]}
    _post("add", {"collection": REGISTRY, "key": page, "lang": "en",
                  "contentMd": body, "meta": meta}, timeout=120)


def seed_cfg(domain: str) -> dict:
    return {
        "enabled": True,
        "interval_min": DEFAULT_INTERVAL_MIN,
        "run_now": False,
        "domain": domain,
        "generator": {"kind": "command", "name": "report-distill",
                      "cmd": "scripts/ada/report-distill.py",
                      "cwd": "chaba", "cost": {"timeout_s": 300}},
        "note": ("nightly L1->L2 domain digest — report-distill "
                 "(canonical chaba copy; supersedes the ada-pi "
                 "scripts/report-distill.py prototype)"),
    }


def _gated(cfg: dict, now: datetime, force: bool, page: str) -> str | None:
    """skip reason or None — flood-news-update.py semantics."""
    if not cfg.get("enabled", True):
        return "disabled"
    if force or cfg.get("run_now"):
        return None
    interval = int(cfg.get("interval_min") or 0)
    last = cfg.get("last_run")
    if interval and last:
        last_ts = _parse_ts(last)
        if last_ts and now.timestamp() < last_ts + interval * 60 - 30:
            return f"interval (last run {last})"
    return None


# -------------------------------------------------------------- sources

def bank_collections() -> list[str]:
    """ada-ha-bank-* collections from the SSOT registry — {instance}
    expands to tony (the CMS bank scope). Falls back to a static list."""
    cols = []
    try:
        text = BANKS_SSOT.read_text()
        for m in _COLL_KEY_RX.finditer(text):
            coll = m.group(1).replace("{instance}", "tony")
            if coll.startswith("ada-ha-bank-"):
                cols.append(coll)
    except OSError as e:
        print(f"warn: cannot read {BANKS_SSOT} ({e}) — static bank list",
              file=sys.stderr)
    if not cols:
        cols = ["ada-ha-bank-general", "ada-ha-bank-home",
                "ada-ha-bank-people", "ada-ha-bank-projects-tony",
                "ada-ha-bank-devin-tony"]
    return sorted(dict.fromkeys(cols))


def collect_deltas(collection: str, since_ts: float) -> tuple[int, list]:
    """-> (n_changed, rows). Rows carry key/title/epoch — no bodies.
    Private collections return counts only."""
    try:
        docs = _search_all(collection)
    except Exception as e:
        print(f"  warn: {collection} unreachable ({e})", file=sys.stderr)
        return -1, []
    changed = [d for d in docs if _epoch(d) > since_ts]
    changed.sort(key=_epoch, reverse=True)
    rows = [{"key": d.get("key") or "?",
             "title": _meta(d, "title") or _meta(d, "summary"),
             "status": _meta(d, "status") or "active",
             "epoch": _epoch(d)} for d in changed]
    return len(changed), rows


# --------------------------------------------------------------- render

def render_digest(dom: str, members: list[dict], deltas: list[tuple],
                  since_ts: float, prev_slug: str | None,
                  now: datetime) -> tuple[str, str]:
    """-> (body, summary-line). deltas = [(collection, n, rows)]."""
    stale = [d for d in members if is_stale(d, now)]
    n_delta = sum(n for _, n, _ in deltas if n > 0)
    stamp = now.strftime("%Y-%m-%d %H:%M")
    since_s = datetime.fromtimestamp(
        since_ts, timezone.utc).strftime("%m-%d %H:%MZ")

    lines = [f"# {dom} digest — {stamp}Z", "",
             f"**Updated:** {stamp}Z", "",
             f"{len(members)} {dom} pages, {len(stale)} stale"
             + (f" · {n_delta} bank deltas since {since_s}"
                if deltas else "") + ".",
             ""]
    if prev_slug:
        lines += [f"Supersedes `{prev_slug}` (archived snapshot).", ""]

    lines += ["## Pages", ""]
    for d in members[:MAX_MEMBERS]:
        slug = _meta(d, "slug") or d.get("key")
        flag = " ⚠STALE" if is_stale(d, now) else ""
        conf = _meta(d, "confidence")
        conf_s = f" [{conf}]" if conf else ""
        links = ", ".join(_meta_list(d, "links")[:6])
        links_s = f" → {links}" if links else ""
        lines.append(
            f"- **{_meta(d, 'title') or slug}** (`{slug}`){flag}{conf_s}"
            f" — {_meta(d, 'summary') or '—'} "
            f"({_meta(d, 'updated')[:16]}){links_s}")
    if len(members) > MAX_MEMBERS:
        lines.append(f"- …and {len(members) - MAX_MEMBERS} more")
    if not members:
        lines.append("_None._")
    lines.append("")

    if deltas:
        lines += [f"## Bank deltas since {since_s}", ""]
        for coll, n, rows in deltas:
            if n < 0:
                lines.append(f"- `{coll}` — unreachable")
                continue
            if n == 0:
                lines.append(f"- `{coll}` — none")
                continue
            if PRIVATE_COLL_RX.search(coll):
                lines.append(f"- `{coll}` — {n} docs changed "
                             "(private bank — counts only)")
                continue
            shown = ", ".join(
                f"`{r['key']}`"
                + (f" ({r['status']})" if r["status"] != "active" else "")
                for r in rows[:MAX_DELTAS])
            more = f" …+{n - MAX_DELTAS}" if n > MAX_DELTAS else ""
            lines.append(f"- `{coll}` — {n} changed: {shown}{more}")
        lines.append("")

    lines += ["## Timeline", "",
              f"- {now.isoformat(timespec='seconds')[:16]} digest refreshed:"
              f" {len(members)} pages, {len(stale)} stale"
              + (f", {n_delta} deltas" if deltas else ""), "",
              f"*Generated by report-distill.py · {stamp}Z · sources: "
              f"ada-cms-pages"
              + (f" + {len(deltas)} collections" if deltas else "")
              + "*"]
    summary = (f"{len(members)} {dom} pages, {len(stale)} stale"
               + (f", {n_delta} bank deltas since {since_s}"
                  if deltas else ""))
    return "\n".join(lines), summary[:240]


# --------------------------------------------------------------- publish

def archive_previous(dom: str, old: dict, today: str) -> str | None:
    """Snapshot the previous digest under its own date slug when it was
    last updated on an earlier day. Returns the archive slug or None."""
    old_updated = _meta(old, "updated")
    old_date = old_updated[:10]
    if not re.match(r"\d{4}-\d{2}-\d{2}", old_date) or old_date >= today:
        return None
    slug = f"{dom}-digest"
    arch_key = f"{slug}-{old_date}"
    try:
        existing = _post("get", {"collection": COLLECTION, "key": arch_key,
                                 "lang": "en"})
        if existing:
            return arch_key  # snapshot already exists for that date
    except Exception:
        pass
    meta = {k: (v if isinstance(v, list) else [str(v)])
            for k, v in (old.get("meta") or {}).items()}
    meta.update({
        "status": ["superseded"], "superseded_by": [slug],
        "slug": [arch_key], "subject": [arch_key],
        "title": [f"{dom.title()} digest — {old_date} snapshot"],
        "lang": ["en"],
        # updated stays at the original stamp — time-of-event honesty.
        "last_verified": [today],
    })
    note = (f"> Archived snapshot of `{slug}` as of {old_updated[:16]} — "
            f"superseded by the refreshed digest. Do not edit.\n\n")
    _post("add", {"collection": COLLECTION, "key": arch_key, "lang": "en",
                  "contentMd": note + (old.get("contentMd") or ""),
                  "meta": meta}, timeout=60)
    return arch_key


def prune_archives(dom: str, docs: list[dict], now: datetime) -> list[str]:
    """Flip <dom>-digest-YYYY-MM-DD snapshots older than KEEP_DAYS to
    status: archived (never delete — superseded manual merges got
    archived, same convention). Returns flipped slugs."""
    flipped = []
    for d in docs:
        m = _ARCHIVE_KEY_RX.match(d.get("key") or "")
        if not m or m.group(1) != dom:
            continue
        if _meta(d, "status") != "superseded":
            continue
        try:
            age = (now.date() - datetime.strptime(
                m.group(2), "%Y-%m-%d").date()).days
        except ValueError:
            continue
        if age <= KEEP_DAYS:
            continue
        meta = {k: (v if isinstance(v, list) else [str(v)])
                for k, v in (d.get("meta") or {}).items()}
        meta["status"] = ["archived"]
        meta["last_verified"] = [now.date().isoformat()]
        _post("add", {"collection": COLLECTION, "key": d["key"],
                      "lang": d.get("lang") or "en",
                      "contentMd": d.get("contentMd") or "",
                      "meta": meta}, timeout=60)
        flipped.append(d["key"])
    return flipped


def publish_digest(dom: str, body: str, summary: str, members: list[dict],
                   delta_colls: list[str], prev_slug: str | None,
                   old: dict | None, now: datetime, cfg: dict) -> dict:
    """Merge-meta upsert of <dom>-digest per the writer contract."""
    slug = f"{dom}-digest"
    meta = {k: (v if isinstance(v, list) else [str(v)])
            for k, v in ((old or {}).get("meta") or {}).items()}
    meta.setdefault("bank", ["cms"])
    meta.setdefault("scope", ["tony"])
    meta.setdefault("source", ["api"])
    meta.setdefault("status", ["active"])
    member_slugs = [_meta(d, "slug") or d.get("key")
                    for d in members[:MAX_LINKS]]
    links = list(member_slugs)
    if prev_slug:
        links.append(prev_slug)
    tl = [x for x in meta.get("timeline", []) if isinstance(x, str)]
    tl.append(f"{now.isoformat(timespec='seconds')[:16]} digest: "
              f"{len(members)} pages"
              + (f", {len(delta_colls)} sources" if delta_colls else ""))
    meta.update({
        "kind": ["report"], "slug": [slug], "subject": [slug],
        "title": [f"{dom.title()} digest"],
        "format": ["markdown"], "lang": ["en"], "domain": [dom],
        # 'summary' is what cms-normalize-meta.page_type(slug) computes
        # for *-digest — divergence causes normalize/writer churn.
        "attribute": ["summary"],
        "summary": [summary],
        "fresh_for": [cfg.get("fresh_for") or "1d"],
        # derived aggregate over member metas — not a measurement
        "confidence": ["medium"],
        "updated": [now.isoformat(timespec="seconds")],
        "last_verified": [now.date().isoformat()],
        "valid_from": meta.get("valid_from")
                      or [now.date().isoformat()],
        "written_by": ["report-distill.py"],
        "generated_by": [f"report-distill.py --domain {dom}"],
        "report_role": ["digest"],
        "sources": ["ada-cms-pages"] + list(delta_colls),
        "links": links,
        "timeline": tl[-TIMELINE_CAP:],
    })
    if prev_slug:
        meta["supersedes"] = [prev_slug]
    _post("add", {"collection": COLLECTION, "key": slug, "lang": "en",
                  "contentMd": body, "meta": meta}, timeout=120)
    return meta


def validate_contract(meta: dict) -> list[str]:
    """meta_contract fields that must be non-blank (report_meta.py
    parity — rejects the write instead of landing a thin page)."""
    return [f for f in ("summary", "domain", "fresh_for", "confidence",
                        "timeline", "updated")
            if not (meta.get(f) or [""])[0]]


# ---------------------------------------------------------------- index

def regen_reports_index() -> bool:
    """Refresh ada-cms-pages/reports-index — same table as
    report-daily-brief.py, plus a status filter so superseded/archived
    snapshots don't crowd live pages."""
    docs = _search_all(COLLECTION)
    now = datetime.now(timezone.utc)
    rows = []
    for d in docs:
        meta = d.get("meta") or {}
        kind = _meta(d, "kind")
        if kind not in ("report", "page"):
            continue
        if _meta(d, "status") in DEAD_STATUS:
            continue
        slug = _meta(d, "slug") or d.get("key") or "?"
        if slug in SKIP_KEYS or _ARCHIVE_KEY_RX.match(slug):
            continue
        ff = _meta(d, "fresh_for")
        upd = _meta(d, "updated")
        stale = False
        ttl = fresh_for_seconds(ff)
        if ttl and upd:
            try:
                dt = datetime.fromisoformat(upd.replace("Z", "+00:00"))
                stale = (now - dt).total_seconds() > ttl
            except ValueError:
                pass
        rows.append({"slug": slug,
                     "title": _meta(d, "title") or slug,
                     "domain": _meta(d, "domain") or "-",
                     "summary": _meta(d, "summary"),
                     "updated": upd[:16] or "-",
                     "fresh": ff or "-", "stale": stale})
    rows.sort(key=lambda r: r["updated"], reverse=True)
    lines = [f"# Reports index — {now:%Y-%m-%d %H:%M}Z\n",
             "Brief summaries of every report page — read the linked page",
             "only when the summary isn't enough.\n",
             "| slug | domain | updated | fresh | summary |",
             "|---|---|---|---|---|"]
    for r in rows[:60]:
        flag = " ⚠STALE" if r["stale"] else ""
        summ = (r["summary"] or r["title"])[:80]
        lines.append(f"| {r['slug']} | {r['domain']} | {r['updated']}"
                     f"{flag} | {r['fresh']} | {summ} |")
    _post("add", {
        "collection": COLLECTION, "key": "reports-index", "lang": "en",
        "contentMd": "\n".join(lines),
        "meta": {
            "kind": ["page"], "slug": ["reports-index"],
            "title": [f"Reports index — {now:%Y-%m-%d %H:%M}Z"],
            "format": ["markdown"], "domain": ["meta"],
            "summary": ["Auto-generated index of report pages — "
                        "slug, domain, staleness, one-line brief."],
            "fresh_for": ["6h"],
            "updated": [now.isoformat(timespec="seconds")],
            "written_by": ["report-distill.py"],
        }}, timeout=60)
    return True


# ----------------------------------------------------------------- main

def process_domain(dom: str, cfg: dict, pages: list[dict], args,
                   now: datetime) -> tuple[int, int]:
    """One domain end-to-end. -> (rc, count)."""
    slug = f"{dom}-digest"
    why = _gated(cfg, now, args.force, slug)
    if why:
        print(f"== {slug}: skipped ({why})")
        return 0, 0

    members = [d for d in pages
               if _meta(d, "domain") == dom
               and _meta(d, "kind") in ("report", "page")
               and _meta(d, "status") not in DEAD_STATUS
               and (d.get("key") or "") not in SKIP_KEYS
               and not _ARCHIVE_KEY_RX.match(d.get("key") or "")
               and (_meta(d, "slug") or d.get("key")) != slug]
    members.sort(key=lambda d: _meta(d, "updated"), reverse=True)

    dom_cfg = dict(DEFAULT_CFG)
    dom_cfg.update(DOMAINS.get(dom) or {})
    if cfg.get("fresh_for"):
        dom_cfg["fresh_for"] = cfg["fresh_for"]

    # delta watermark: registry last_run -> page meta.updated -> 24h.
    old = next((d for d in pages
                if (d.get("key") or "") == slug
                and (d.get("lang") or "en") == "en"), None)
    watermark = (_parse_ts(cfg.get("last_run"))
                 or (_parse_ts(_meta(old, "updated")) if old else None)
                 or now.timestamp() - 86400)

    colls = list(cfg.get("collections") or dom_cfg["collections"])
    if dom_cfg.get("banks"):
        colls = bank_collections() + colls
    colls = list(dict.fromkeys(colls))
    deltas = []
    for c in colls:
        n, rows = collect_deltas(c, watermark)
        deltas.append((c, n, rows))
        print(f"  {c}: {n if n >= 0 else 'unreachable'} changed")

    prev = None if args.dry_run or not old else archive_previous(
        dom, old, now.date().isoformat())
    if prev:
        print(f"  archived previous digest -> {prev}")

    body, summary = render_digest(dom, members, deltas, watermark,
                                  prev, now)
    if args.dry_run:
        print(f"== {slug} [dry-run]\n{body}\n---")
        return 0, len(members)

    if old and _VOLATILE_RX.sub("", body) == \
            _VOLATILE_RX.sub("", old.get("contentMd") or ""):
        print(f"== {slug}: unchanged — meta-only refresh skipped")
        return 0, len(members)

    meta = publish_digest(dom, body, summary, members, colls, prev,
                          old, now, cfg)
    missing = validate_contract(meta)
    if missing:  # unreachable — publish_digest stamps all of them
        print(f"== {slug}: meta contract violation {missing}",
              file=sys.stderr)
        return 2, 0
    pruned = prune_archives(dom, pages, now)
    if pruned:
        print(f"  archived>14d -> status:archived: {', '.join(pruned)}")
    print(f"== {slug}: {len(members)} pages, "
          f"{sum(1 for d in members if is_stale(d, now))} stale"
          + (f", supersedes {prev}" if prev else ""))
    return 0, len(members)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--domain", action="append", default=[],
                    help="process only this domain (repeatable)")
    ap.add_argument("--register", action="store_true",
                    help="seed missing ada-cms-automation docs, no run")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    registry, registry_up = list_registry()
    try:
        pages = _search_all(COLLECTION)
    except Exception as e:
        print(f"error: cannot scan {COLLECTION}: {e}", file=sys.stderr)
        return 2

    domains = set()
    for d in pages:
        if _meta(d, "kind") not in ("report", "page"):
            continue
        if _meta(d, "status") in DEAD_STATUS:
            continue
        key = d.get("key") or ""
        if key in SKIP_KEYS or _ARCHIVE_KEY_RX.match(key):
            continue
        domains.add(_meta(d, "domain") or "uncategorized")
    domains |= set(DOMAINS)
    if args.domain:
        domains &= set(args.domain)
    domains = sorted(domains)

    now = datetime.now(timezone.utc)
    rc = n_pages = 0
    for dom in domains:
        slug = f"{dom}-digest"
        cfg = registry.get(slug)
        if cfg is None:
            cfg = seed_cfg(dom)
            if registry_up and not args.dry_run:
                try:
                    save_registry_doc(slug, cfg)
                    print(f"== {slug}: seeded registry doc")
                except Exception as e:
                    print(f"  warn: registry seed failed ({e})",
                          file=sys.stderr)
        if args.register:
            continue
        started = time.monotonic()

        def write_state(status, count, error=None):
            if args.dry_run or not registry_up:
                return
            st = dict(cfg)
            st.update({"run_now": False,
                       "last_run": now.isoformat(timespec="seconds"),
                       "last_status": status, "last_count": count,
                       "last_duration_s": round(
                           time.monotonic() - started, 1)})
            if error:
                st["last_error"] = str(error)[:500]
            else:
                st.pop("last_error", None)
            try:
                save_registry_doc(slug, st)
            except Exception as e:
                print(f"  warn: registry write-back failed ({e})",
                      file=sys.stderr)

        try:
            rc_, cnt = process_domain(dom, cfg, pages, args, now)
            rc = rc or rc_
            n_pages += cnt
            write_state("ok" if rc_ == 0 else "error", cnt)
        except Exception as e:
            print(f"== {slug}: error {e}", file=sys.stderr)
            write_state("error", 0, e)
            rc = 2

    if args.register:
        print(f"registered {len(domains)} domain digest(s)")
        return 0
    if not args.dry_run and rc == 0:
        try:
            regen_reports_index()
            print("reports-index regenerated")
        except Exception as e:
            print(f"warn: reports-index regen failed ({e})",
                  file=sys.stderr)
    print(f"done — {len(domains)} domain(s), {n_pages} member pages")
    return rc


if __name__ == "__main__":
    sys.exit(main())
