#!/usr/bin/env python3
"""Generate the `ada-tools` CMS page — every tool Ada can call, with
descriptions, grouped by layer.

Sources (parsed, not hand-maintained):
  - ada-pi backend/realtime_provider.py — core declarations (AST-parsed:
    dict literals carrying "name" + "description")
  - ada-pi backend/tools.d/*.py — drop-in DECLARATION dicts
  - ada-pi backend/tools.d/manifest.yml — policy/timeout per drop-in

Page follows the cms-reports standard (docs/ssot/apps/ssot.apps.cms-reports.yml):
H1, อัปเดตล่าสุด line, paired <!-- tools:auto --> managed block, italic
provenance footer, meta generated_by / sources / report_role=leaf /
parent=reports-index.

Usage: tools-report.py [--dry-run]
"""

import ast
import json
import os
import sys
import time
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ADA_PI = Path(os.environ.get("ADA_PI_REPO",
            REPO.parent / "ada-pi"))
PROVIDER = ADA_PI / "backend" / "realtime_provider.py"
TOOLS_D = ADA_PI / "backend" / "tools.d"
MANIFEST = TOOLS_D / "manifest.yml"

MDDB = os.environ.get("MDDB_BASE_URL",
                      "http://100.102.134.91:11023/v1").rstrip("/")
COLLECTION = "ada-cms-pages"
SLUG = "ada-tools"
PARENT = "reports-index"
ICT = timezone(timedelta(hours=7))


def _literal(node):
    try:
        return ast.literal_eval(node)
    except Exception:
        return None


def declarations_in(path):
    """AST-walk a python file; return every dict literal that has both
    'name' and 'description' string values. Only those two values must be
    literal — parameters may be non-literal (constants, calls)."""
    out = {}
    tree = ast.parse(path.read_text())
    for node in ast.walk(tree):
        if not isinstance(node, ast.Dict):
            continue
        vals = {}
        for k, v in zip(node.keys, node.values):
            key = _literal(k)
            if key in ("name", "description"):
                vals[key] = _literal(v)
        name, desc = vals.get("name"), vals.get("description")
        if isinstance(name, str) and isinstance(desc, str):
            out[name] = desc.strip()
    return out


def manifest_policies():
    try:
        import yaml
        data = yaml.safe_load(MANIFEST.read_text()) or {}
        return data.get("tools") or {}
    except Exception:
        return {}


def collect():
    core = declarations_in(PROVIDER)
    drops, meta = {}, {}
    if TOOLS_D.is_dir():
        for f in sorted(TOOLS_D.glob("*.py")):
            for name, desc in declarations_in(f).items():
                if name not in core:
                    drops[name] = desc
                    meta[name] = f.stem
    return core, drops, meta, manifest_policies()


def render(core, drops, dmeta, pols, now):
    lines = ["# Ada Tools",
             f"**อัปเดตล่าสุด:** {now.strftime('%Y-%m-%d %H:%M')}",
             "",
             "<!-- tools:auto -->",
             "",
             "Every tool Ada can call in a voice session. Generated from "
             "the declaration sources — do not hand-edit inside this block.",
             "",
             f"## Core tools ({len(core)})",
             "",
             "Declared inline in `backend/realtime_provider.py`.",
             ""]
    for name in sorted(core):
        lines.append(f"* **{name}** — {core[name]}")
    if drops:
        lines += ["", f"## Drop-in tools ({len(drops)})", "",
                  "`backend/tools.d/` — module + manifest entry; policy "
                  "column shows the access tier.", "",
                  "| tool | policy | module | description |",
                  "|---|---|---|---|"]
        for name in sorted(drops):
            p = pols.get(name) or {}
            policy = p.get("policy", "?") if isinstance(p, dict) else "?"
            desc = drops[name].replace("|", "\\|")
            lines.append(f"| {name} | {policy} | {dmeta[name]} | {desc} |")
    lines += ["", "<!-- /tools:auto -->", "",
              f"*Generated by tools-report.py · "
              f"{now.isoformat(timespec='seconds')} · sources: "
              "ada-pi backend/realtime_provider.py, backend/tools.d/*, "
              "tools.d/manifest.yml*"]
    return "\n".join(lines)


def publish(title, content, now):
    meta = {
        "attribute": ["page"], "bank": ["cms"], "domain": ["infra"],
        "format": ["markdown"], "instance": ["ada"], "kind": ["page"],
        "lang": ["en"], "scope": ["tony"], "slug": [SLUG],
        "source": ["api"], "status": ["active"], "subject": [SLUG],
        "title": [title],
        "updated": [now.isoformat(timespec="seconds")],
        "valid_from": [now.date().isoformat()],
        "last_verified": [now.date().isoformat()],
        "written_by": ["tools-report"],
        "generated_by": ["tools-report.py"],
        "sources": ["ada-pi backend/realtime_provider.py",
                    "ada-pi backend/tools.d/*",
                    "ada-pi backend/tools.d/manifest.yml"],
        "report_role": ["leaf"],
        "parent": [PARENT],
    }
    body = json.dumps({"collection": COLLECTION, "key": SLUG, "lang": "en",
                       "contentMd": content, "meta": meta}).encode()
    req = urllib.request.Request(f"{MDDB}/add", data=body,
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.status


def main():
    started = time.monotonic()
    now = datetime.now(timezone.utc).astimezone(ICT)
    core, drops, dmeta, pols = collect()
    if not core:
        sys.exit(f"no core declarations parsed from {PROVIDER} — "
                 f"ADA_PI_REPO={ADA_PI}")
    content = render(core, drops, dmeta, pols, now)
    title = "Ada Tools"
    if "--dry-run" in sys.argv:
        print(content)
        return
    code = publish(title, content, datetime.now(timezone.utc))
    print(f"{SLUG}: HTTP {code} ({len(content)} chars, "
          f"{len(core)} core + {len(drops)} drop-in tools, "
          f"{time.monotonic()-started:.1f}s)")


main()
