#!/usr/bin/env python3
"""Build an archive-distillation manifest for a source repo.

Walks the tree, hashes every file (sha256), and classifies each into a
topic bucket via a rules table. Output:
  docs/archive/manifests/<repo>.yml

Rules per ssot.apps.archive-distillation.yml: every file appears
exactly once — consumed by a topic report or declared excluded-noise.
audit.unaccounted must be 0.

Usage:
  python3 scripts/archive-inventory.py <source-dir> <repo-name> [--commit SHA]
"""
import hashlib, json, sys, fnmatch
from pathlib import Path

# (glob pattern, topic) — first match wins. 'excluded-noise' = declared drop.
RULES = [
    ("docs/dns/**", "network-dns"),
    ("docs/*url*.json", "network-dns"),
    ("docs/idc1-vpn.json", "network-dns"),
    ("docs/host-*.json", "host-infrastructure"),
    ("docs/stacks-*.json", "host-infrastructure"),
    ("docs/idc1-stack.json", "host-infrastructure"),
    ("docs/*runbook*", "operations-runbooks"),
    ("docs/docker-management.md", "operations-runbooks"),
    ("docs/backlog.md", "operations-runbooks"),
    ("docs/README.md", "operations-runbooks"),
    ("docs/dev-host.md", "operations-runbooks"),
    ("docs/*reorganization*", "reorg-methodology"),
    ("docs/system-inventory/**", "host-infrastructure"),
    ("docs/line-webhook-deployment.md", "deployment"),
    ("docs/mcp-nodehost.md", "deployment"),
    ("docs/**", "host-infrastructure"),
    ("stacks/**", "host-infrastructure"),
    ("scripts/**", "operations-runbooks"),
    ("sites/**", "sites-apps"),
    ("mcp/mcp-playwright/**", "excluded-noise"),
    ("mcp/**", "mcp-ecosystem"),
    ("tmp/**", "excluded-noise"),
    ("temp*/**", "excluded-noise"),
    ("temp_*", "excluded-noise"),
    ("pulls/**", "excluded-noise"),
    ("utputFormat", "excluded-noise"),
    ("audidoc-pdfs/**", "excluded-noise"),
    ("requirements/**", "excluded-noise"),
    ("src/__init__.py", "excluded-noise"),
    ("docker/**", "host-infrastructure"),
    ("tools/**", "operations-runbooks"),
    ("templates/**", "host-infrastructure"),
    (".env.template", "host-infrastructure"),
    ("installer/**", "deployment"),
    ("archive/**", "mcp-ecosystem"),
    ("devops-mcp.http", "mcp-ecosystem"),
    ("*.md", "operations-runbooks"),
    ("package-lock.json", "excluded-noise"),
    ("**/package-lock.json", "excluded-noise"),
    ("**/node_modules/**", "excluded-noise"),
    ("**/modules.old/**", "excluded-noise"),
    (".git*", "excluded-noise"),
    (".*ignore", "excluded-noise"),
]

def classify(path):
    for pat, topic in RULES:
        if fnmatch.fnmatch(path, pat):
            return topic
    return "unclassified"

def main(src, repo, commit=None):
    src = Path(src).resolve()
    files = []
    for p in sorted(src.rglob("*")):
        if not p.is_file() or ".git" in p.parts:
            continue
        rel = str(p.relative_to(src))
        h = hashlib.sha256(p.read_bytes()).hexdigest()[:16]
        files.append({"path": rel, "sha256": h, "size": p.stat().st_size,
                      "topic": classify(rel)})
    from collections import Counter
    topics = Counter(f["topic"] for f in files)
    manifest = {
        "repo": repo, "commit": commit or "unknown",
        "files": files,
        "audit": {"total_files": len(files),
                  "by_topic": dict(topics.most_common()),
                  "unaccounted": topics.get("unclassified", 0)},
    }
    out = Path(f"/home/tony/CascadeProjects/chaba/docs/archive/manifests/{repo}.yml")
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        f.write(f"# Inventory manifest — {repo}\n")
        f.write(f"# generated by scripts/archive-inventory.py\n")
        f.write(json.dumps(manifest, indent=1))
    print(f"wrote {out}: {len(files)} files, unclassified={topics.get('unclassified',0)}")
    for t, n in topics.most_common():
        print(f"  {t}: {n}")

if __name__ == "__main__":
    src, repo = sys.argv[1], sys.argv[2]
    commit = sys.argv[3] if len(sys.argv) > 3 else None
    main(src, repo, commit)
