#!/usr/bin/env python3
"""Refresh mcp-debug efficiency baselines by running mcp_savings and updating the baselines SSOT."""
import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
from mcp_debug.config import BASELINES
from mcp_debug.tools import mcp_savings, _replace_section, _section_yaml


def main():
    parser = argparse.ArgumentParser(description="Refresh mcp-debug baselines")
    parser.add_argument(
        "--update-baselines",
        type=lambda x: x.lower() == "true",
        default=False,
        help="Update ssot.mcp-debug.baselines.yml with new baselines (default: false)",
    )
    args = parser.parse_args()

    savings = mcp_savings([])
    if not savings.get("ok"):
        print("mcp_savings failed", file=sys.stderr)
        sys.exit(1)

    print(json.dumps(savings, indent=2, default=str))

    if not args.update_baselines:
        return

    # Reorganise per-host output into per-command structures.
    by_command = {}
    for host, hdata in savings.get("hosts", {}).items():
        for command, s in hdata.get("commands", {}).items():
            by_command.setdefault(command, {})[host] = s

    commands_cfg = {}
    for command, hosts in by_command.items():
        baseline = hosts.get("tony_omen") or list(hosts.values())[0]
        savings_pcts = [h.get("savings_pct_chars", 0) for h in hosts.values()]
        recommended = all(p > 0 for p in savings_pcts)

        commands_cfg[command] = {
            "raw_words": baseline["raw_words"],
            "compact_words": baseline["compact_words"],
            "savings_pct": baseline["savings_pct"],
            "raw_chars": baseline["raw_chars"],
            "compact_chars": baseline["compact_chars"],
            "savings_pct_chars": baseline["savings_pct_chars"],
            "recommended": recommended,
            "hosts": {
                h: {
                    "raw_words": s["raw_words"],
                    "compact_words": s["compact_words"],
                    "savings_pct": s["savings_pct"],
                    "raw_chars": s["raw_chars"],
                    "compact_chars": s["compact_chars"],
                    "savings_pct_chars": s["savings_pct_chars"],
                }
                for h, s in hosts.items()
            },
        }

    efficiency = {
        "tracked_by": "mcp_stats",
        "note": f"per-host baselines generated on {datetime.now().strftime('%Y-%m-%d')} via mcp_savings",
        "commands": commands_cfg,
    }

    workflow = {
        "recommended": [c for c, d in commands_cfg.items() if d.get("recommended")],
        "not_recommended": [c for c, d in commands_cfg.items() if not d.get("recommended")],
    }

    if not BASELINES.exists():
        BASELINES.parent.mkdir(parents=True, exist_ok=True)
        BASELINES.write_text(
            "title: MCP Debug Baselines\n"
            "subtitle: Generated per-host raw/compact savings baselines for mcp_debug commands\n"
            "icon: bug\n"
            "version: 1\n"
            "note: Generated by mcp_vet and mcp-debug-refresh-baselines.py. This is runtime data, not canonical policy.\n\n"
        )

    ssot_text = BASELINES.read_text()
    ssot_text = _replace_section(ssot_text, "efficiency", _section_yaml("efficiency", efficiency))
    ssot_text = _replace_section(ssot_text, "workflow", _section_yaml("workflow", workflow))

    with open(BASELINES, "w") as f:
        f.write(ssot_text)

    print("Updated:", BASELINES)
    print("Recommended:", workflow["recommended"])
    print("Not recommended:", workflow["not_recommended"])


if __name__ == "__main__":
    main()
