#!/bin/bash
echo "========================================"
echo "🚀 Skill Creator - IDC1 Deployment"
echo "========================================"
echo ""
echo "This will deploy the Skill Creator UI to idc1.surf-thailand.com"
echo ""
echo "Files created for deployment:"
echo "   📄 deploy-to-idc1.sh - Automated deployment script"
echo "   📄 caddy-skills-config.txt - Caddy configuration snippet"
echo "   📄 DEPLOY_IDC1.md - Full deployment guide"
echo ""
echo "========================================"
echo "Quick Deploy Commands (run on idc1):"
echo "========================================"
echo ""
echo "1. Copy files to idc1:"
echo "   scp deploy-to-idc1.sh chaba@idc1.surf-thailand.com:/tmp/"
echo "   scp caddy-skills-config.txt chaba@idc1.surf-thailand.com:/tmp/"
echo ""
echo "2. SSH to idc1 and run:"
echo "   ssh chaba@idc1.surf-thailand.com"
echo "   sudo /tmp/deploy-to-idc1.sh"
echo ""
echo "3. Or manually:"
echo "   # Start server"
echo "   cd /home/chaba/chaba/services/autoagent/control-panel"
echo "   WIKI_API_URL=http://localhost:3008 nohup /home/chaba/chaba/.venv/bin/python control-server.py --port 8090 &"
echo ""
echo "   # Edit Caddyfile"
echo "   sudo nano /etc/caddy/Caddyfile"
echo "   # Add: handle_path /skills/* { reverse_proxy 127.0.0.1:8090 }"
echo ""
echo "   # Reload Caddy"
echo "   sudo caddy validate --config /etc/caddy/Caddyfile"
echo "   sudo systemctl reload caddy"
echo ""
echo "========================================"
echo "Access URLs after deployment:"
echo "========================================"
echo "   https://assistance.idc1.surf-thailand.com/skills"
echo ""
echo "========================================"
echo "Features available:"
echo "========================================"
echo "   🇹🇭 Thai Language Templates"
echo "   📋 Review/Approval Workflow"
echo "   🎯 LLM-powered Skill Interpretation"
echo "   💾 Wiki Integration"
echo ""
