services:
  web:
    container_name: web
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/srv/public
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
